/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthcareHubDashboardRouteImport } from './routes/healthcare-hub-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WellnessIndexRouteImport } from './routes/wellness/index'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as ModulesIndexRouteImport } from './routes/modules/index'
import { Route as LabIndexRouteImport } from './routes/lab/index'
import { Route as ComplianceIndexRouteImport } from './routes/compliance/index'
import { Route as BillingIndexRouteImport } from './routes/billing/index'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as WellnessSleepRouteImport } from './routes/wellness/sleep'
import { Route as WellnessProfileRouteImport } from './routes/wellness/profile'
import { Route as WellnessMoodRouteImport } from './routes/wellness/mood'
import { Route as WellnessMeditateRouteImport } from './routes/wellness/meditate'
import { Route as WellnessFitnessRouteImport } from './routes/wellness/fitness'
import { Route as PatientsIdRouteImport } from './routes/patients/$id'
import { Route as ModulesSurakshaWebPortalRouteImport } from './routes/modules/suraksha-web-portal'
import { Route as ModulesSurakshaPatientRouteImport } from './routes/modules/suraksha-patient'
import { Route as ModulesSurakshaAshaRouteImport } from './routes/modules/suraksha-asha'
import { Route as ModulesHospitalEhrRouteImport } from './routes/modules/hospital-ehr'
import { Route as ModulesHealthcareHubRouteImport } from './routes/modules/healthcare-hub'
import { Route as AppointmentsIdRouteImport } from './routes/appointments/$id'
import { Route as PatientsIdPrescriptionsRouteImport } from './routes/patients/$id/prescriptions'
import { Route as PatientsIdLabRouteImport } from './routes/patients/$id/lab'
import { Route as PatientsIdEhrRouteImport } from './routes/patients/$id/ehr'
import { Route as PatientsIdBillingRouteImport } from './routes/patients/$id/billing'
import { Route as PatientsIdAppointmentsRouteImport } from './routes/patients/$id/appointments'
import { Route as ModulesHospitalEhrSectionRouteImport } from './routes/modules/hospital-ehr/$section'
import { Route as ModulesHospitalEhrSectionSubsectionRouteImport } from './routes/modules/hospital-ehr/$section/$subsection'

const HealthcareHubDashboardRoute = HealthcareHubDashboardRouteImport.update({
  id: '/healthcare-hub-dashboard',
  path: '/healthcare-hub-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessIndexRoute = WellnessIndexRouteImport.update({
  id: '/wellness/',
  path: '/wellness/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceIndexRoute = ComplianceIndexRouteImport.update({
  id: '/compliance/',
  path: '/compliance/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessSleepRoute = WellnessSleepRouteImport.update({
  id: '/wellness/sleep',
  path: '/wellness/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessProfileRoute = WellnessProfileRouteImport.update({
  id: '/wellness/profile',
  path: '/wellness/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessMoodRoute = WellnessMoodRouteImport.update({
  id: '/wellness/mood',
  path: '/wellness/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessMeditateRoute = WellnessMeditateRouteImport.update({
  id: '/wellness/meditate',
  path: '/wellness/meditate',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessFitnessRoute = WellnessFitnessRouteImport.update({
  id: '/wellness/fitness',
  path: '/wellness/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesSurakshaWebPortalRoute =
  ModulesSurakshaWebPortalRouteImport.update({
    id: '/modules/suraksha-web-portal',
    path: '/modules/suraksha-web-portal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModulesSurakshaPatientRoute = ModulesSurakshaPatientRouteImport.update({
  id: '/modules/suraksha-patient',
  path: '/modules/suraksha-patient',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesSurakshaAshaRoute = ModulesSurakshaAshaRouteImport.update({
  id: '/modules/suraksha-asha',
  path: '/modules/suraksha-asha',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesHospitalEhrRoute = ModulesHospitalEhrRouteImport.update({
  id: '/modules/hospital-ehr',
  path: '/modules/hospital-ehr',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesHealthcareHubRoute = ModulesHealthcareHubRouteImport.update({
  id: '/modules/healthcare-hub',
  path: '/modules/healthcare-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIdRoute = AppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdPrescriptionsRoute = PatientsIdPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PatientsIdRoute,
} as any)
const PatientsIdLabRoute = PatientsIdLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => PatientsIdRoute,
} as any)
const PatientsIdEhrRoute = PatientsIdEhrRouteImport.update({
  id: '/ehr',
  path: '/ehr',
  getParentRoute: () => PatientsIdRoute,
} as any)
const PatientsIdBillingRoute = PatientsIdBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PatientsIdRoute,
} as any)
const PatientsIdAppointmentsRoute = PatientsIdAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientsIdRoute,
} as any)
const ModulesHospitalEhrSectionRoute =
  ModulesHospitalEhrSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => ModulesHospitalEhrRoute,
  } as any)
const ModulesHospitalEhrSectionSubsectionRoute =
  ModulesHospitalEhrSectionSubsectionRouteImport.update({
    id: '/$subsection',
    path: '/$subsection',
    getParentRoute: () => ModulesHospitalEhrSectionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/healthcare-hub-dashboard': typeof HealthcareHubDashboardRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/modules/healthcare-hub': typeof ModulesHealthcareHubRoute
  '/modules/hospital-ehr': typeof ModulesHospitalEhrRouteWithChildren
  '/modules/suraksha-asha': typeof ModulesSurakshaAshaRoute
  '/modules/suraksha-patient': typeof ModulesSurakshaPatientRoute
  '/modules/suraksha-web-portal': typeof ModulesSurakshaWebPortalRoute
  '/patients/$id': typeof PatientsIdRouteWithChildren
  '/wellness/fitness': typeof WellnessFitnessRoute
  '/wellness/meditate': typeof WellnessMeditateRoute
  '/wellness/mood': typeof WellnessMoodRoute
  '/wellness/profile': typeof WellnessProfileRoute
  '/wellness/sleep': typeof WellnessSleepRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/billing/': typeof BillingIndexRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/lab/': typeof LabIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/wellness/': typeof WellnessIndexRoute
  '/modules/hospital-ehr/$section': typeof ModulesHospitalEhrSectionRouteWithChildren
  '/patients/$id/appointments': typeof PatientsIdAppointmentsRoute
  '/patients/$id/billing': typeof PatientsIdBillingRoute
  '/patients/$id/ehr': typeof PatientsIdEhrRoute
  '/patients/$id/lab': typeof PatientsIdLabRoute
  '/patients/$id/prescriptions': typeof PatientsIdPrescriptionsRoute
  '/modules/hospital-ehr/$section/$subsection': typeof ModulesHospitalEhrSectionSubsectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthcare-hub-dashboard': typeof HealthcareHubDashboardRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/modules/healthcare-hub': typeof ModulesHealthcareHubRoute
  '/modules/hospital-ehr': typeof ModulesHospitalEhrRouteWithChildren
  '/modules/suraksha-asha': typeof ModulesSurakshaAshaRoute
  '/modules/suraksha-patient': typeof ModulesSurakshaPatientRoute
  '/modules/suraksha-web-portal': typeof ModulesSurakshaWebPortalRoute
  '/patients/$id': typeof PatientsIdRouteWithChildren
  '/wellness/fitness': typeof WellnessFitnessRoute
  '/wellness/meditate': typeof WellnessMeditateRoute
  '/wellness/mood': typeof WellnessMoodRoute
  '/wellness/profile': typeof WellnessProfileRoute
  '/wellness/sleep': typeof WellnessSleepRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/billing': typeof BillingIndexRoute
  '/compliance': typeof ComplianceIndexRoute
  '/lab': typeof LabIndexRoute
  '/modules': typeof ModulesIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/wellness': typeof WellnessIndexRoute
  '/modules/hospital-ehr/$section': typeof ModulesHospitalEhrSectionRouteWithChildren
  '/patients/$id/appointments': typeof PatientsIdAppointmentsRoute
  '/patients/$id/billing': typeof PatientsIdBillingRoute
  '/patients/$id/ehr': typeof PatientsIdEhrRoute
  '/patients/$id/lab': typeof PatientsIdLabRoute
  '/patients/$id/prescriptions': typeof PatientsIdPrescriptionsRoute
  '/modules/hospital-ehr/$section/$subsection': typeof ModulesHospitalEhrSectionSubsectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/healthcare-hub-dashboard': typeof HealthcareHubDashboardRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/modules/healthcare-hub': typeof ModulesHealthcareHubRoute
  '/modules/hospital-ehr': typeof ModulesHospitalEhrRouteWithChildren
  '/modules/suraksha-asha': typeof ModulesSurakshaAshaRoute
  '/modules/suraksha-patient': typeof ModulesSurakshaPatientRoute
  '/modules/suraksha-web-portal': typeof ModulesSurakshaWebPortalRoute
  '/patients/$id': typeof PatientsIdRouteWithChildren
  '/wellness/fitness': typeof WellnessFitnessRoute
  '/wellness/meditate': typeof WellnessMeditateRoute
  '/wellness/mood': typeof WellnessMoodRoute
  '/wellness/profile': typeof WellnessProfileRoute
  '/wellness/sleep': typeof WellnessSleepRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/billing/': typeof BillingIndexRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/lab/': typeof LabIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/wellness/': typeof WellnessIndexRoute
  '/modules/hospital-ehr/$section': typeof ModulesHospitalEhrSectionRouteWithChildren
  '/patients/$id/appointments': typeof PatientsIdAppointmentsRoute
  '/patients/$id/billing': typeof PatientsIdBillingRoute
  '/patients/$id/ehr': typeof PatientsIdEhrRoute
  '/patients/$id/lab': typeof PatientsIdLabRoute
  '/patients/$id/prescriptions': typeof PatientsIdPrescriptionsRoute
  '/modules/hospital-ehr/$section/$subsection': typeof ModulesHospitalEhrSectionSubsectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthcare-hub-dashboard'
    | '/appointments/$id'
    | '/modules/healthcare-hub'
    | '/modules/hospital-ehr'
    | '/modules/suraksha-asha'
    | '/modules/suraksha-patient'
    | '/modules/suraksha-web-portal'
    | '/patients/$id'
    | '/wellness/fitness'
    | '/wellness/meditate'
    | '/wellness/mood'
    | '/wellness/profile'
    | '/wellness/sleep'
    | '/analytics/'
    | '/appointments/'
    | '/billing/'
    | '/compliance/'
    | '/lab/'
    | '/modules/'
    | '/patients/'
    | '/wellness/'
    | '/modules/hospital-ehr/$section'
    | '/patients/$id/appointments'
    | '/patients/$id/billing'
    | '/patients/$id/ehr'
    | '/patients/$id/lab'
    | '/patients/$id/prescriptions'
    | '/modules/hospital-ehr/$section/$subsection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthcare-hub-dashboard'
    | '/appointments/$id'
    | '/modules/healthcare-hub'
    | '/modules/hospital-ehr'
    | '/modules/suraksha-asha'
    | '/modules/suraksha-patient'
    | '/modules/suraksha-web-portal'
    | '/patients/$id'
    | '/wellness/fitness'
    | '/wellness/meditate'
    | '/wellness/mood'
    | '/wellness/profile'
    | '/wellness/sleep'
    | '/analytics'
    | '/appointments'
    | '/billing'
    | '/compliance'
    | '/lab'
    | '/modules'
    | '/patients'
    | '/wellness'
    | '/modules/hospital-ehr/$section'
    | '/patients/$id/appointments'
    | '/patients/$id/billing'
    | '/patients/$id/ehr'
    | '/patients/$id/lab'
    | '/patients/$id/prescriptions'
    | '/modules/hospital-ehr/$section/$subsection'
  id:
    | '__root__'
    | '/'
    | '/healthcare-hub-dashboard'
    | '/appointments/$id'
    | '/modules/healthcare-hub'
    | '/modules/hospital-ehr'
    | '/modules/suraksha-asha'
    | '/modules/suraksha-patient'
    | '/modules/suraksha-web-portal'
    | '/patients/$id'
    | '/wellness/fitness'
    | '/wellness/meditate'
    | '/wellness/mood'
    | '/wellness/profile'
    | '/wellness/sleep'
    | '/analytics/'
    | '/appointments/'
    | '/billing/'
    | '/compliance/'
    | '/lab/'
    | '/modules/'
    | '/patients/'
    | '/wellness/'
    | '/modules/hospital-ehr/$section'
    | '/patients/$id/appointments'
    | '/patients/$id/billing'
    | '/patients/$id/ehr'
    | '/patients/$id/lab'
    | '/patients/$id/prescriptions'
    | '/modules/hospital-ehr/$section/$subsection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthcareHubDashboardRoute: typeof HealthcareHubDashboardRoute
  AppointmentsIdRoute: typeof AppointmentsIdRoute
  ModulesHealthcareHubRoute: typeof ModulesHealthcareHubRoute
  ModulesHospitalEhrRoute: typeof ModulesHospitalEhrRouteWithChildren
  ModulesSurakshaAshaRoute: typeof ModulesSurakshaAshaRoute
  ModulesSurakshaPatientRoute: typeof ModulesSurakshaPatientRoute
  ModulesSurakshaWebPortalRoute: typeof ModulesSurakshaWebPortalRoute
  PatientsIdRoute: typeof PatientsIdRouteWithChildren
  WellnessFitnessRoute: typeof WellnessFitnessRoute
  WellnessMeditateRoute: typeof WellnessMeditateRoute
  WellnessMoodRoute: typeof WellnessMoodRoute
  WellnessProfileRoute: typeof WellnessProfileRoute
  WellnessSleepRoute: typeof WellnessSleepRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  BillingIndexRoute: typeof BillingIndexRoute
  ComplianceIndexRoute: typeof ComplianceIndexRoute
  LabIndexRoute: typeof LabIndexRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  WellnessIndexRoute: typeof WellnessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/healthcare-hub-dashboard': {
      id: '/healthcare-hub-dashboard'
      path: '/healthcare-hub-dashboard'
      fullPath: '/healthcare-hub-dashboard'
      preLoaderRoute: typeof HealthcareHubDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness/': {
      id: '/wellness/'
      path: '/wellness'
      fullPath: '/wellness/'
      preLoaderRoute: typeof WellnessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/': {
      id: '/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/': {
      id: '/compliance/'
      path: '/compliance'
      fullPath: '/compliance/'
      preLoaderRoute: typeof ComplianceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness/sleep': {
      id: '/wellness/sleep'
      path: '/wellness/sleep'
      fullPath: '/wellness/sleep'
      preLoaderRoute: typeof WellnessSleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness/profile': {
      id: '/wellness/profile'
      path: '/wellness/profile'
      fullPath: '/wellness/profile'
      preLoaderRoute: typeof WellnessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness/mood': {
      id: '/wellness/mood'
      path: '/wellness/mood'
      fullPath: '/wellness/mood'
      preLoaderRoute: typeof WellnessMoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness/meditate': {
      id: '/wellness/meditate'
      path: '/wellness/meditate'
      fullPath: '/wellness/meditate'
      preLoaderRoute: typeof WellnessMeditateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness/fitness': {
      id: '/wellness/fitness'
      path: '/wellness/fitness'
      fullPath: '/wellness/fitness'
      preLoaderRoute: typeof WellnessFitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/suraksha-web-portal': {
      id: '/modules/suraksha-web-portal'
      path: '/modules/suraksha-web-portal'
      fullPath: '/modules/suraksha-web-portal'
      preLoaderRoute: typeof ModulesSurakshaWebPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/suraksha-patient': {
      id: '/modules/suraksha-patient'
      path: '/modules/suraksha-patient'
      fullPath: '/modules/suraksha-patient'
      preLoaderRoute: typeof ModulesSurakshaPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/suraksha-asha': {
      id: '/modules/suraksha-asha'
      path: '/modules/suraksha-asha'
      fullPath: '/modules/suraksha-asha'
      preLoaderRoute: typeof ModulesSurakshaAshaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/hospital-ehr': {
      id: '/modules/hospital-ehr'
      path: '/modules/hospital-ehr'
      fullPath: '/modules/hospital-ehr'
      preLoaderRoute: typeof ModulesHospitalEhrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/healthcare-hub': {
      id: '/modules/healthcare-hub'
      path: '/modules/healthcare-hub'
      fullPath: '/modules/healthcare-hub'
      preLoaderRoute: typeof ModulesHealthcareHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$id': {
      id: '/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/appointments/$id'
      preLoaderRoute: typeof AppointmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id/prescriptions': {
      id: '/patients/$id/prescriptions'
      path: '/prescriptions'
      fullPath: '/patients/$id/prescriptions'
      preLoaderRoute: typeof PatientsIdPrescriptionsRouteImport
      parentRoute: typeof PatientsIdRoute
    }
    '/patients/$id/lab': {
      id: '/patients/$id/lab'
      path: '/lab'
      fullPath: '/patients/$id/lab'
      preLoaderRoute: typeof PatientsIdLabRouteImport
      parentRoute: typeof PatientsIdRoute
    }
    '/patients/$id/ehr': {
      id: '/patients/$id/ehr'
      path: '/ehr'
      fullPath: '/patients/$id/ehr'
      preLoaderRoute: typeof PatientsIdEhrRouteImport
      parentRoute: typeof PatientsIdRoute
    }
    '/patients/$id/billing': {
      id: '/patients/$id/billing'
      path: '/billing'
      fullPath: '/patients/$id/billing'
      preLoaderRoute: typeof PatientsIdBillingRouteImport
      parentRoute: typeof PatientsIdRoute
    }
    '/patients/$id/appointments': {
      id: '/patients/$id/appointments'
      path: '/appointments'
      fullPath: '/patients/$id/appointments'
      preLoaderRoute: typeof PatientsIdAppointmentsRouteImport
      parentRoute: typeof PatientsIdRoute
    }
    '/modules/hospital-ehr/$section': {
      id: '/modules/hospital-ehr/$section'
      path: '/$section'
      fullPath: '/modules/hospital-ehr/$section'
      preLoaderRoute: typeof ModulesHospitalEhrSectionRouteImport
      parentRoute: typeof ModulesHospitalEhrRoute
    }
    '/modules/hospital-ehr/$section/$subsection': {
      id: '/modules/hospital-ehr/$section/$subsection'
      path: '/$subsection'
      fullPath: '/modules/hospital-ehr/$section/$subsection'
      preLoaderRoute: typeof ModulesHospitalEhrSectionSubsectionRouteImport
      parentRoute: typeof ModulesHospitalEhrSectionRoute
    }
  }
}

interface ModulesHospitalEhrSectionRouteChildren {
  ModulesHospitalEhrSectionSubsectionRoute: typeof ModulesHospitalEhrSectionSubsectionRoute
}

const ModulesHospitalEhrSectionRouteChildren: ModulesHospitalEhrSectionRouteChildren =
  {
    ModulesHospitalEhrSectionSubsectionRoute:
      ModulesHospitalEhrSectionSubsectionRoute,
  }

const ModulesHospitalEhrSectionRouteWithChildren =
  ModulesHospitalEhrSectionRoute._addFileChildren(
    ModulesHospitalEhrSectionRouteChildren,
  )

interface ModulesHospitalEhrRouteChildren {
  ModulesHospitalEhrSectionRoute: typeof ModulesHospitalEhrSectionRouteWithChildren
}

const ModulesHospitalEhrRouteChildren: ModulesHospitalEhrRouteChildren = {
  ModulesHospitalEhrSectionRoute: ModulesHospitalEhrSectionRouteWithChildren,
}

const ModulesHospitalEhrRouteWithChildren =
  ModulesHospitalEhrRoute._addFileChildren(ModulesHospitalEhrRouteChildren)

interface PatientsIdRouteChildren {
  PatientsIdAppointmentsRoute: typeof PatientsIdAppointmentsRoute
  PatientsIdBillingRoute: typeof PatientsIdBillingRoute
  PatientsIdEhrRoute: typeof PatientsIdEhrRoute
  PatientsIdLabRoute: typeof PatientsIdLabRoute
  PatientsIdPrescriptionsRoute: typeof PatientsIdPrescriptionsRoute
}

const PatientsIdRouteChildren: PatientsIdRouteChildren = {
  PatientsIdAppointmentsRoute: PatientsIdAppointmentsRoute,
  PatientsIdBillingRoute: PatientsIdBillingRoute,
  PatientsIdEhrRoute: PatientsIdEhrRoute,
  PatientsIdLabRoute: PatientsIdLabRoute,
  PatientsIdPrescriptionsRoute: PatientsIdPrescriptionsRoute,
}

const PatientsIdRouteWithChildren = PatientsIdRoute._addFileChildren(
  PatientsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthcareHubDashboardRoute: HealthcareHubDashboardRoute,
  AppointmentsIdRoute: AppointmentsIdRoute,
  ModulesHealthcareHubRoute: ModulesHealthcareHubRoute,
  ModulesHospitalEhrRoute: ModulesHospitalEhrRouteWithChildren,
  ModulesSurakshaAshaRoute: ModulesSurakshaAshaRoute,
  ModulesSurakshaPatientRoute: ModulesSurakshaPatientRoute,
  ModulesSurakshaWebPortalRoute: ModulesSurakshaWebPortalRoute,
  PatientsIdRoute: PatientsIdRouteWithChildren,
  WellnessFitnessRoute: WellnessFitnessRoute,
  WellnessMeditateRoute: WellnessMeditateRoute,
  WellnessMoodRoute: WellnessMoodRoute,
  WellnessProfileRoute: WellnessProfileRoute,
  WellnessSleepRoute: WellnessSleepRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  BillingIndexRoute: BillingIndexRoute,
  ComplianceIndexRoute: ComplianceIndexRoute,
  LabIndexRoute: LabIndexRoute,
  ModulesIndexRoute: ModulesIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  WellnessIndexRoute: WellnessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
