"""Initial migration

Revision ID: b554416b9212
Revises: 
Create Date: 2025-08-17 21:50:29.629432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b554416b9212'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_records_id'), table_name='billing_records')
    op.drop_table('billing_records')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_dvrs_id'), table_name='dvrs')
    op.drop_table('dvrs')
    op.drop_index(op.f('ix_usage_records_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_tenant_settings_id'), table_name='tenant_settings')
    op.drop_table('tenant_settings')
    op.drop_index(op.f('ix_tenant_users_id'), table_name='tenant_users')
    op.drop_table('tenant_users')
    op.drop_index(op.f('ix_dvr_channels_id'), table_name='dvr_channels')
    op.drop_table('dvr_channels')
    op.drop_index(op.f('ix_notification_recipients_id'), table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_tenant_id'), table_name='notification_recipients')
    op.drop_table('notification_recipients')
    op.drop_index(op.f('ix_addons_slug'), table_name='addons')
    op.drop_table('addons')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=200), nullable=False),
    sa.Column('subdomain', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('plan', sa.VARCHAR(length=12), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contact_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('billing_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('billing_address', sqlite.JSON(), nullable=True),
    sa.Column('tax_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('settings', sqlite.JSON(), nullable=True),
    sa.Column('limits', sqlite.JSON(), nullable=True),
    sa.Column('features', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('trial_ends_at', sa.DATETIME(), nullable=True),
    sa.Column('subscription_ends_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('addons',
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('installed', sa.BOOLEAN(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('installed_at', sa.DATETIME(), nullable=True),
    sa.Column('enabled_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_addons_slug'), 'addons', ['slug'], unique=False)
    op.create_table('notification_recipients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=50), nullable=True),
    sa.Column('push_token', sa.VARCHAR(length=500), nullable=True),
    sa.Column('preferences', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_recipients_tenant_id'), 'notification_recipients', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_recipients_id'), 'notification_recipients', ['id'], unique=False)
    op.create_table('dvr_channels',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dvr_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('rtsp_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('hls_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('ingest_active', sa.BOOLEAN(), nullable=True),
    sa.Column('last_probe_ok', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dvr_id'], ['dvrs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dvr_channels_id'), 'dvr_channels', ['id'], unique=False)
    op.create_table('tenant_users',
    sa.Column('id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=True),
    sa.Column('permissions', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('invited_at', sa.DATETIME(), nullable=True),
    sa.Column('accepted_at', sa.DATETIME(), nullable=True),
    sa.Column('meta_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_users_id'), 'tenant_users', ['id'], unique=False)
    op.create_table('tenant_settings',
    sa.Column('id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('features_enabled', sqlite.JSON(), nullable=True),
    sa.Column('limits', sqlite.JSON(), nullable=True),
    sa.Column('preferences', sqlite.JSON(), nullable=True),
    sa.Column('security_settings', sqlite.JSON(), nullable=True),
    sa.Column('compliance_settings', sqlite.JSON(), nullable=True),
    sa.Column('notification_settings', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_settings_id'), 'tenant_settings', ['id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('metric', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=True),
    sa.Column('period_start', sa.DATETIME(), nullable=False),
    sa.Column('period_end', sa.DATETIME(), nullable=False),
    sa.Column('meta_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_id'), 'usage_records', ['id'], unique=False)
    op.create_table('dvrs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('host', sa.VARCHAR(length=100), nullable=False),
    sa.Column('port', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=200), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dvrs_id'), 'dvrs', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('plan', sa.VARCHAR(length=12), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('billing_cycle', sa.VARCHAR(length=7), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('current_period_start', sa.DATETIME(), nullable=True),
    sa.Column('current_period_end', sa.DATETIME(), nullable=True),
    sa.Column('trial_start', sa.DATETIME(), nullable=True),
    sa.Column('trial_end', sa.DATETIME(), nullable=True),
    sa.Column('cancelled_at', sa.DATETIME(), nullable=True),
    sa.Column('meta_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('billing_records',
    sa.Column('id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('subscription_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('stripe_invoice_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('billing_period_start', sa.DATETIME(), nullable=True),
    sa.Column('billing_period_end', sa.DATETIME(), nullable=True),
    sa.Column('meta_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_index(op.f('ix_billing_records_id'), 'billing_records', ['id'], unique=False)
    # ### end Alembic commands ###
