import { pgTable, index, timestamp, text, uuid, integer, boolean, jsonb } from 'drizzle-orm/pg-core';

export const patients = pgTable('patients', {
  id: uuid('id').defaultRandom().primaryKey(),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  email: text('email').unique(),
  phone: text('phone'),
  dateOfBirth: timestamp('date_of_birth'),
  gender: text('gender'),
  address: text('address'),
  city: text('city'),
  state: text('state'),
  zipCode: text('zip_code'),
  country: text('country').default('USA'),
  medicalRecordNumber: text('medical_record_number').unique(),
  insuranceId: text('insurance_id'),
  primaryCarePhysician: text('primary_care_physician'),
  emergencyContactName: text('emergency_contact_name'),
  emergencyContactPhone: text('emergency_contact_phone'),
  allergies: jsonb('allergies'),
  medications: jsonb('medications'),
  conditions: jsonb('conditions'),
  status: text('status').default('active'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
}, (table) => [
  index('idx_patients_email').on(table.email),
  index('idx_patients_mrn').on(table.medicalRecordNumber),
  index('idx_patients_name').on(table.lastName, table.firstName),
  index('idx_patients_status').on(table.status),
  index('idx_patients_created_at').on(table.createdAt),
]);

export const appointments = pgTable('appointments', {
  id: uuid('id').defaultRandom().primaryKey(),
  patientId: uuid('patient_id').references(() => patients.id),
  providerId: text('provider_id'),
  departmentId: text('department_id'),
  appointmentType: text('appointment_type'),
  reason: text('reason').notNull(),
  status: text('status').default('scheduled'),
  scheduledAt: timestamp('scheduled_at').notNull(),
  duration: integer('duration').default(30),
  notes: text('notes'),
  isTelemedicine: boolean('is_telemedicine').default(false),
  telemedicineUrl: text('telemedicine_url'),
  checkedInAt: timestamp('checked_in_at'),
  cancelledAt: timestamp('cancelled_at'),
  cancelReason: text('cancel_reason'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
}, (table) => [
  index('idx_appointments_patient').on(table.patientId),
  index('idx_appointments_status').on(table.status),
  index('idx_appointments_scheduled').on(table.scheduledAt),
  index('idx_appointments_provider').on(table.providerId),
  index('idx_appointments_created_at').on(table.createdAt),
]);

export const clinicalNotes = pgTable('clinical_notes', {
  id: uuid('id').defaultRandom().primaryKey(),
  patientId: uuid('patient_id').references(() => patients.id),
  appointmentId: uuid('appointment_id').references(() => appointments.id),
  providerId: text('provider_id').notNull(),
  noteType: text('note_type').notNull(),
  subjective: text('subjective'),
  objective: text('objective'),
  assessment: text('assessment'),
  plan: text('plan'),
  icdCodes: jsonb('icd_codes'),
  cptCodes: jsonb('cpt_codes'),
  signedAt: timestamp('signed_at'),
  signedBy: text('signed_by'),
  status: text('status').default('draft'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
}, (table) => [
  index('idx_clinical_notes_patient').on(table.patientId),
  index('idx_clinical_notes_appointment').on(table.appointmentId),
  index('idx_clinical_notes_provider').on(table.providerId),
  index('idx_clinical_notes_status').on(table.status),
  index('idx_clinical_notes_created_at').on(table.createdAt),
]);

export const prescriptions = pgTable('prescriptions', {
  id: uuid('id').defaultRandom().primaryKey(),
  patientId: uuid('patient_id').references(() => patients.id),
  providerId: text('provider_id').notNull(),
  medicationId: text('medication_id'),
  medicationName: text('medication_name').notNull(),
  dosage: text('dosage').notNull(),
  frequency: text('frequency').notNull(),
  route: text('route'),
  quantity: integer('quantity'),
  refills: integer('refills').default(0),
  refillsRemaining: integer('refills_remaining'),
  instructions: text('instructions'),
  startDate: timestamp('start_date').defaultNow(),
  endDate: timestamp('end_date'),
  status: text('status').default('active'),
  pharmacyId: text('pharmacy_id'),
  prescribedAt: timestamp('prescribed_at').defaultNow(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
}, (table) => [
  index('idx_prescriptions_patient').on(table.patientId),
  index('idx_prescriptions_provider').on(table.providerId),
  index('idx_prescriptions_status').on(table.status),
  index('idx_prescriptions_medication').on(table.medicationName),
  index('idx_prescriptions_created_at').on(table.createdAt),
]);

export const vitalSigns = pgTable('vital_signs', {
  id: uuid('id').defaultRandom().primaryKey(),
  patientId: uuid('patient_id').references(() => patients.id),
  appointmentId: uuid('appointment_id').references(() => appointments.id),
  providerId: text('provider_id'),
  recordedAt: timestamp('recorded_at').defaultNow(),
  bloodPressureSystolic: integer('blood_pressure_systolic'),
  bloodPressureDiastolic: integer('blood_pressure_diastolic'),
  heartRate: integer('heart_rate'),
  respiratoryRate: integer('respiratory_rate'),
  temperature: text('temperature'),
  temperatureUnit: text('temperature_unit').default('F'),
  oxygenSaturation: integer('oxygen_saturation'),
  weight: text('weight'),
  weightUnit: text('weight_unit').default('lbs'),
  height: text('height'),
  heightUnit: text('height_unit').default('in'),
  bmi: text('bmi'),
  painLevel: integer('pain_level'),
  notes: text('notes'),
  createdAt: timestamp('created_at').defaultNow(),
}, (table) => [
  index('idx_vital_signs_patient').on(table.patientId),
  index('idx_vital_signs_appointment').on(table.appointmentId),
  index('idx_vital_signs_recorded_at').on(table.recordedAt),
]);

export const labResults = pgTable('lab_results', {
  id: uuid('id').defaultRandom().primaryKey(),
  patientId: uuid('patient_id').references(() => patients.id),
  orderId: uuid('order_id'),
  testName: text('test_name').notNull(),
  testCode: text('test_code'),
  category: text('category'),
  value: text('value'),
  unit: text('unit'),
  referenceRange: text('reference_range'),
  status: text('status').default('pending'),
  resultDate: timestamp('result_date'),
  notes: text('notes'),
  isAbnormal: boolean('is_abnormal').default(false),
  flags: jsonb('flags'),
  performedAt: timestamp('performed_at'),
  reportedAt: timestamp('reported_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
}, (table) => [
  index('idx_lab_results_patient').on(table.patientId),
  index('idx_lab_results_order').on(table.orderId),
  index('idx_lab_results_status').on(table.status),
  index('idx_lab_results_category').on(table.category),
  index('idx_lab_results_result_date').on(table.resultDate),
  index('idx_lab_results_created_at').on(table.createdAt),
]);

export const charges = pgTable('charges', {
  id: uuid('id').defaultRandom().primaryKey(),
  patientId: uuid('patient_id').references(() => patients.id),
  appointmentId: uuid('appointment_id').references(() => appointments.id),
  invoiceId: uuid('invoice_id'),
  serviceDate: timestamp('service_date').defaultNow(),
  serviceCode: text('service_code').notNull(),
  description: text('description'),
  quantity: integer('quantity').default(1),
  unitPrice: text('unit_price').notNull(),
  totalAmount: text('total_amount').notNull(),
  insuranceAdjustment: text('insurance_adjustment'),
  patientResponsibility: text('patient_responsibility'),
  status: text('status').default('pending'),
  cptCodes: jsonb('cpt_codes'),
  icdCodes: jsonb('icd_codes'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
}, (table) => [
  index('idx_charges_patient').on(table.patientId),
  index('idx_charges_invoice').on(table.invoiceId),
  index('idx_charges_status').on(table.status),
  index('idx_charges_service_date').on(table.serviceDate),
  index('idx_charges_created_at').on(table.createdAt),
]);

export const auditLogs = pgTable('audit_logs', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: text('user_id'),
  userEmail: text('user_email'),
  action: text('action').notNull(),
  resourceType: text('resource_type').notNull(),
  resourceId: text('resource_id'),
  details: jsonb('details'),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  timestamp: timestamp('timestamp').defaultNow(),
  status: text('status').default('success'),
  errorMessage: text('error_message'),
}, (table) => [
  index('idx_audit_logs_user').on(table.userId),
  index('idx_audit_logs_action').on(table.action),
  index('idx_audit_logs_resource').on(table.resourceType, table.resourceId),
  index('idx_audit_logs_timestamp').on(table.timestamp),
  index('idx_audit_logs_created_at').on(table.createdAt),
]);

export const mfaSecrets = pgTable('mfa_secrets', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: text('user_id').unique().notNull(),
  secret: text('secret').notNull(),
  backupCodes: text('backup_codes').notNull(),
  enabled: boolean('enabled').default(false),
  verifiedAt: timestamp('verified_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
}, (table) => [
  index('idx_mfa_secrets_user').on(table.userId),
]);
